services:

  db:
    image: mysql:8
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_pass
      - MYSQL_DATABASE=budget_tracker
    ports:
      - "13306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - db_data:/var/lib/mysql

  mail-dev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"


volumes:
    db_data:
